{{- range .Values.permissions.clusterRoles }}
{{- if and $.Values.serviceAccount.bind .create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator-olm-v1.clusterRoleName" $ }}{{ if eq .type "grantor" }}-grantor{{ end }}-cr
  labels:
    {{- include "operator-olm-v1.labels" $ | nindent 4 }}
    app.kubernetes.io/component: cluster-role
    {{- if eq .type "grantor" }}
    app.kubernetes.io/component-type: grantor
    {{- else }}
    app.kubernetes.io/component-type: operator
    {{- end }}
rules:
  {{- if .customRules }}
  {{- toYaml .customRules | nindent 2 }}
  {{- else }}
  # Default minimal permissions for OLMv1 operator installation
  - apiGroups: [olm.operatorframework.io]
    resources: [clusterextensions/finalizers]
    verbs: [update]
  {{- end }}
{{- end }}
{{- end }}

---
{{- range .Values.permissions.clusterRoles }}
{{- if and $.Values.serviceAccount.bind .create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "operator-olm-v1.clusterRoleName" $ }}{{ if eq .type "grantor" }}-grantor{{ end }}-crb
  labels:
    {{- include "operator-olm-v1.labels" $ | nindent 4 }}
    app.kubernetes.io/component: cluster-role-binding
    {{- if eq .type "grantor" }}
    app.kubernetes.io/component-type: grantor
    {{- else }}
    app.kubernetes.io/component-type: operator
    {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "operator-olm-v1.serviceAccountName" $ }}
    namespace: {{ $.Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "operator-olm-v1.clusterRoleName" $ }}{{ if eq .type "grantor" }}-grantor{{ end }}-cr
{{- end }}
{{- end }}