{{- if .Values.clusterRole.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator-olm-v1.fullname" . }}-{{ .Values.clusterRole.name }}
  labels:
    {{- include "operator-olm-v1.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "5"
rules:
  {{- if .Values.clusterRole.customRules }}
  {{- toYaml .Values.clusterRole.customRules | nindent 2 }}
  {{- else }}
  # Default minimal permissions for OLMv1 operator installation
  - apiGroups: [olm.operatorframework.io]
    resources: [clusterextensions/finalizers]
    verbs: [update]
  {{- end }}
{{- end }}
---
{{- if .Values.clusterRoleRBAC.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "operator-olm-v1.fullname" . }}-{{ .Values.clusterRoleRBAC.name }}
  labels:
    {{- include "operator-olm-v1.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": post-delete
    "helm.sh/hook-weight": "5"
rules:
  {{- if .Values.clusterRoleRBAC.customRules }}
  {{- toYaml .Values.clusterRoleRBAC.customRules | nindent 4 }}
  {{- end }}
{{- end }}