{{- if .Values.roleBinding.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "operator-olm-v1.fullname" . }}-{{ .Values.roleBinding.name }}
  labels:
    {{- include "operator-olm-v1.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "operator-olm-v1.fullname" . }}-{{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "operator-olm-v1.fullname" . }}-{{ .Values.role.name }}
{{- end }}
---
{{- if .Values.roleBindingRBAC.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "operator-olm-v1.fullname" . }}-{{ .Values.roleBindingRBAC.name }}
  labels:
    {{- include "operator-olm-v1.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "operator-olm-v1.fullname" . }}-{{ .Values.serviceAccount.name }}
    namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "operator-olm-v1.fullname" . }}-{{ .Values.roleRBAC.name }}
{{- end }}

