{{- if .Values.serviceAccount.create }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "operator-olm-v1.serviceAccountName" . }}
  namespace: {{ .Values.operator.namespace }}
  labels:
    {{- include "operator-olm-v1.labels" . | nindent 4 }}
    app.kubernetes.io/component: service-account
    {{- with .Values.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
