kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: olmv1-manager-clusterrolebinding
  annotations:
    description: "Binds users to the OLMv1 manager ClusterRole for operator deployment capabilities"
subjects:
  # You can specify more than one "subject" if you want to grant access to multiple users or groups
  # - kind: User
  #   name: "username@company.com" # Name is case sensitive
  #   apiGroup: rbac.authorization.k8s.io
  
  # - kind: Group
  #   name: "developers" # Name is case sensitive
  #   apiGroup: rbac.authorization.k8s.io

  
  # - kind: ServiceAccount
  #   name: "olmv1-user" # Name is case sensitive
  #   namespace: "namespace"
  #   apiGroup: ""
roleRef:
  kind: ClusterRole
  name: olmv1-manager-clusterrole
  apiGroup: rbac.authorization.k8s.io