apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/managed-by: rbac-manager
    app.kubernetes.io/name: argocd-operator
    olmv1: argocd-operator-installer
  name: argocd-operator-installer
  namespace: argo-operator